### ISSUE TITLE
looking for details from apple gpu 9 (M3)

### ISSUE THREAD

**Issue by adonishong** [philipturner/metal-benchmarks#4]
Fantastic works, thanks to creator of this repository @philipturner , looking forward to get detail from apple gpu 9

**Comment by philipturner** [comment]
Likely next summer when I will work on researching the architecture for a living. Until then, the best documentation out there is Apple's developer videos.

**Comment by philipturner** [comment]
https://github.com/philipturner/metal-benchmarks/commit/e83e8280ee6f8c0c16264beb10c0c4580cfc16fc
