### ISSUE TITLE
Number of cores about Apple M1 Pro

### ISSUE THREAD

**Issue by akshaygulabrao** [philipturner/metal-benchmarks#6]
Excellent work and writing!

I have a question about the number of cores on the Apple M1 Pro (which I am running). 

According to `sysctl`, I have 6 performance cores
<img width="552" alt="image" src="https://github.com/user-attachments/assets/e0856f13-fb9a-4b03-bc3b-36eec272a4b0">

and 2 efficiency cores
<img width="540" alt="image" src="https://github.com/user-attachments/assets/bd95dae2-3433-498e-9ea7-0b937945d3b9">

According to this [Apple article](https://www.apple.com/newsroom/2021/10/introducing-m1-pro-and-m1-max-the-most-powerful-chips-apple-has-ever-built/), I ought to have 10 cores total. 
![image](https://github.com/user-attachments/assets/2793ecaf-7856-4611-9c85-c850d0c004df)

According to your work, I ought to have 16 cores total. 
<img width="663" alt="Screenshot 2024-09-22 at 2 15 54 PM" src="https://github.com/user-attachments/assets/fa2d0185-6c39-417c-9a18-39a9593e4e12">

As a sanity check, I have verified that I DO in fact have the Apple M1 Pro
![image](https://github.com/user-attachments/assets/0d923f8c-b194-44f3-bc6b-2f30851142e9)

Would you be able to help reconcile my confusion?

**Comment by akshaygulabrao** [comment]
After a little research, I answered my own question. The 14-inch Macbook M1 Pro models come with 2 fewer performance cores. The GPU still has 8 cores (similar to the 16-inch model).  According to #5 , you only count the GPU cores + CPU performance cores, which would be 14 cores for the 14-inch model

**Comment by philipturner** [comment]
I don't count the CPU cores in anything. It's `metal-benchmarks`. Metal only runs on the GPU.

**Comment by philipturner** [comment]
https://github.com/philipturner/metal-benchmarks/commit/9128e8add2cc186949fdc954a63630fd1b1d8343
